# Generated by Django 3.2.7 on 2022-12-08 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_auto_20221208_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rubric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='transport.rubric', verbose_name='Рубрика'),
        ),
    ]
